export const columnIds = [
  'lastUpdate',
  'underlier',
  'spotFut',
  'basis',
  'spotUsed',
  'ae',
  'productType',
  'expiry',
  'expiryFull',
  'strike',
  'strikeP',
  'pc',
  'ratio',
  'bid',
  'premium',
  'ask',
  'vol',
  'volOffset',
  'size',
  'contract',
  'delta$',
  'gamma$',
  'vega',
  'theta$',
  'theta',
  'fx$',
  'premP',
  'premT',
  'skew$',
  'smile$',
  'volGeoSkew',
  'volGeoSmile',
  'hedgeRic',
  'futsMat',
  'futsCt',
  'vanna$',
  'volga$',
  'pnl10',
  'pnl20',
  'pnl30',
  'rho',
  'dv01',
  'divRho$',
  'optionRic',
  'created',
  'openclose',
  'settlementType'
];

export const columnSettings = {
  lastUpdate: { label:'Last Update', type:'date', category:'' },
  underlier: { label:'Underlier', type:'string', category:'input edited', },
  spotFut: { label:'Spot/ Fut', type:'string', category:'price' },
  basis: { label:'Basis', type:'number', category:'price' },
  spotUsed: { label:'Spot Used', type:'number', category:'price' },
  ae: { label:'A/E', type:'string', category:'input' },
  productType: { label:'Product Type', type:'string', category:'input edited' },
  expiry: { label:'Expiry', type:'date', category:'input edited' },
  expiryFull: { label:'Expiry(Full)', type:'date', category:'input' },
  strike: { label:'Strike', type:'string', category:'input edited' },
  strikeP: { label:'Strike %', type:'number', category:'price' },
  pc: { label:'Put/Call', type:'string', category:'' },
  ratio: { label:'Ratio', type:'string', category:'input' },
  bid: { label:'Bid', type:'date', category:'bidask' },
  premium: { label:'Premium', type:'number', category:'price' },
  ask: { label:'Ask', type:'number', category:'bidask' },
  vol: { label:'Vol', type:'number', category:'price' },
  volOffset: { label:'Vol Offset', type:'number', category:'input' },
  size: { label:'Size', type:'number', category:'input' },
  contract: { label:'Multiplier', type:'number', category:'input' },
  delta$: { label:'Delta $', type:'number', category:'risk' },
  gamma$: { label:'Gamma $', type:'number', category:'risk' },
  vega: { label:'Vega', type:'number', category:'risk' },
  vega$: { label:'Vega $', type:'number', category:'risk' },
  theta$: { label:'Theta $', type:'number', category:'risk' },
  theta: { label:'Theta', type:'number', category:'risk' },
  fx$: { label:'FX USD 1', type:'number', category:'risk' },
  premP: { label:'Prem %', type:'number', category:'risk' },
  premT: { label:'Prem Total', type:'number', category:'risk' },
  skew$: { label:'Skew$', type:'number', category:'risk' },
  smile$: { label:'Smile$', type:'number', category:'risk' },
  volGeoSkew: { label:'VolGeoSkew', type:'number', category:'risk' },
  volGeoSmile: { label:'volGeoSmile', type:'number', category:'risk' },
  hedgeRic: { label:'Hedge Ric', type:'string', category:'input' },
  futsMat: { label:'Futs Mat', type:'date', category:'' },
  futsCt: { label:'Fut Sz', type:'number', category:'risk' },
  vanna$: { label:'Vanna $', type:'number', category:'risk' },
  volga$: { label:'Volga $', type:'number', category:'risk' },
  pnl10: { label:'Pnl Slide -10%', type:'number', category:'' },
  pnl20: { label:'Pnl Slide -20%', type:'number', category:'' },
  pnl30: { label:'Pnl Slide -30%', type:'number', category:'' },
  rho: { label:'Rho', type:'date', style:'number', category:'risk' },
  dv01: { label:'DV01 USD', type:'number', category:'risk' },
  divRho$: { label:'DivRho USD', type:'number', category:'risk' },
  optionRic: { label:'Option Ric', type:'string', category:'' },
  created: { label:'Created', type:'string', category:'' },
  openclose: { label:'Open/ Close', type:'string', category:'' },
  settlementType: { label:'Cash', type:'string', category:'' }
};

export const rfq1 = {
  isExpanded: false,
  legs: [
    {
      lastUpdate: '',
      underlier: '',
      spotFut: 'f',
      basis: '-0.76',
      spotUsed: '7,574.26',
      ae: '',
      productType: '',
      expiry: '',
      expiryFull: '',
      strike: '7600',
      strikeP: '199.02%',
      pc: 'C',
      ratio: '1',
      bid: '',
      premium: '-56.24',
      ask: '',
      vol: '94.14%',
      volOffset: '',
      delta: '-17.88',
      size: '1',
      contract: '100',
      delta$: '348,921.95',
      gamma$: '123,374.52',
      vega: '0',
      vega$: '976.83',
      theta$: '-175.5',
      theta: '0.13',
      fx$: '1,3079',
      premP: '',
      premT: '5,090.18',
      skew$: '-19.32',
      smile$: '-0.24',
      volGeoSkew: '-0.39',
      volGeoSmile: '-0.04',
      hedgeRic: '',
      futsMat: '',
      futsCt: '10',
      vanna$: '21.48',
      volga$: '1.58',
      pnl10: '-6,657.47',
      pnl20: '6,657.24',
      pnl30: '6,657.20',
      rho: '-0.98',
      dv01: '2.78',
      divRho$: '277.67',
      optionRic: 'LFE7600B0.L',
      created: '',
      openclose: '',
      settlementType: ''
    },
    {
      lastUpdate: '',
      underlier: '',
      spotFut: 'f',
      basis: '-0.76',
      spotUsed: '7,574.26',
      ae: '',
      productType: '',
      expiry: '',
      expiryFull: '',
      strike: '7500',
      strikeP: '100.34%',
      pc: 'C',
      ratio: '-1',
      bid: '',
      premium: '-62.81',
      ask: '',
      vol: '11.02%',
      volOffset: '',
      delta: '41.12%',
      size: '-1',
      contract: '10',
      delta$: '407,368.94',
      gamma$: '135,900.61',
      vega: '8.3',
      vega$: '1,085.37',
      theta$: '-96.83',
      theta: '-1.5',
      fx$: '1,3079',
      premP: '0.83%',
      premT: '6,280.70',
      skew$: '-15.75',
      smile$: '-0.30',
      volGeoSkew: '-0.12',
      volGeoSmile: '0',
      hedgeRic: '',
      futsMat: '',
      futsCt: '10',
      vanna$: '10.93',
      volga$: '2.56',
      pnl10: '-8,213.98',
      pnl20: '-8,213.21',
      pnl30: '-8,213.21',
      rho: '2.47',
      dv01: '3.23',
      divRho$: '322.70',
      optionRic: 'LFE7600B0.L',
      created: '',
      openclose: '',
      settlementType: ''
    },
    {
      lastUpdate: '17:03:09',
      underlier: '.FTSE',
      spotFut: 'f',
      basis: '-0.76',
      spotUsed: '7,574.26',
      ae: 'E',
      productType: 'CS',
      expiry: 'Feb20',
      expiryFull: 'Fri 21 Feb 20',
      strike: '7600 / 7500',
      strikeP: '',
      pc: 'CS',
      ratio: '1 / -1',
      bid: '',
      premium: '-119.05',
      ask: '',
      vol: '',
      volOffset: '',
      delta: '59%',
      size: '1',
      contract: '',
      delta$: '-58,446.99',
      gamma$: '-12,526.1',
      vega: '8.3',
      vega$: '-108.54',
      theta$: '-21.33',
      theta: '-1.63',
      fx$: '1,3079',
      premP: '1.57%',
      premT: '1,190.51',
      skew$: '-3.57',
      smile$: '-0.54',
      volGeoSkew: '-0.27',
      volGeoSmile: '0.04',
      hedgeRic: 'FFIH0',
      futsMat: '2020-03-20',
      futsCt: '10',
      vanna$: '10.56',
      volga$: '-0.98',
      pnl10: '1,556.51',
      pnl20: '1,557.01',
      pnl30: '1,557.01',
      rho: '3.44',
      dv01: '-0.45',
      divRho$: '-45.03',
      optionRic: 'LFE7500B0.L',
      created: '2020-01-24 16:54',
      openclose: 'Open',
      settlementType: 'Cash'
    }
  ]
}

export const rfq2 = {
  legs: [{
    lastUpdate: '16:50:09',
    underlier: '.SPX',
    spotFut: 'f',
    basis: '-0.76',
    spotUsed: '3,311.73',
    ae: 'E',
    productType: 'P',
    expiry: 'Feb20',
    expiryFull: 'Fri 21 Feb 20',
    strike: '3200',
    strikeP: '96.63%',
    pc: 'P',
    ratio: '1',
    bid: '',
    premium: '16.48',
    ask: '',
    vol: '16%',
    volOffset: '',
    delta: '-20.4',
    size: '1',
    contract: '100',
    delta$: '-67,548.34',
    gamma$: '22,214.52',
    vega: '2.61',
    vega$: '261.27',
    theta$: '-63.75',
    theta: '-0.64',
    fx$: '1',
    premP: '0.5%',
    premT: '1,648.49',
    skew$: '23.8',
    smile$: '6.03',
    volGeoSkew: '0.24',
    volGeoSmile: '0.06',
    hedgeRic: 'ESH0',
    futsMat: '2020-03-20',
    futsCt: '50',
    vanna$: '-33.91',
    volga$: '10.53',
    pnl10: '20,648.54',
    pnl20: '53,528.46',
    pnl30: '86,656.74',
    rho: '-0.54',
    dv01: '-0.54',
    divRho$: '-53.5',
    optionRic: 'SPXWn212032000.U',
    created: '2020-01-24 16:50',
    openclose: 'Open',
    settlementType: 'Cash'
  }],
}

export const rfq3 = {
  legs: [{
    lastUpdate: '16:41:38',
    underlier: '.FTSE',
    spotFut: 'f',
    basis: '-0.76',
    spotUsed: '7,589.81',
    ae: 'E',
    productType: 'C',
    expiry: 'Apr20',
    expiryFull: 'Fri 17 Apr 20',
    strike: '7475',
    strikeP: '98.49%',
    pc: 'C',
    ratio: '-1',
    bid: '',
    premium: '169.8',
    ask: '',
    vol: '11%',
    volOffset: '',
    delta: '53.62%',
    size: '-1',
    contract: '10',
    delta$: '-53,177.86',
    gamma$: '-7,604.49',
    vega: '14.37',
    vega$: '-187.78',
    theta$: '12.16',
    theta: '-0.93',
    fx$: '1.3066',
    premP: '2.24%',
    premT: '-1,698.03',
    skew$: '-1.67',
    smile$: '-0.12',
    volGeoSkew: '0.13',
    volGeoSmile: '0.01',
    hedgeRic: 'FFIH0',
    futsMat: '2020-03-20',
    futsCt: '10',
    vanna$: '3.83',
    volga$: '-1.15',
    pnl10: '2,173.61',
    pnl20: '2,218.63',
    pnl30: '2,218.64',
    rho: '8.86',
    dv01: '-1.16',
    divRho$: '-115.72',
    optionRic: 'LFE7475DO.L',
    created: '2020-01-24 16:41',
    openclose: 'Open',
    settlementType: 'Cash'
  }],
}

export const rfq4 = {
  isExpanded: true,
  legs: [
    {
      lastUpdate: '',
      underlier: '',
      spotFut: 'f',
      basis: '-0.76',
      spotUsed: '7,574.26',
      ae: '',
      productType: '',
      expiry: '',
      expiryFull: '',
      strike: '7600',
      strikeP: '199.02%',
      pc: 'C',
      ratio: '1',
      bid: '',
      premium: '-56.24',
      ask: '',
      vol: '94.14%',
      volOffset: '',
      delta: '-17.88',
      size: '1',
      contract: '100',
      delta$: '348,921.95',
      gamma$: '123,374.52',
      vega: '0',
      vega$: '976.83',
      theta$: '-175.5',
      theta: '0.13',
      fx$: '1,3079',
      premP: '',
      premT: '5,090.18',
      skew$: '-19.32',
      smile$: '-0.24',
      volGeoSkew: '-0.39',
      volGeoSmile: '-0.04',
      hedgeRic: '',
      futsMat: '',
      futsCt: '10',
      vanna$: '21.48',
      volga$: '1.58',
      pnl10: '-6,657.47',
      pnl20: '6,657.24',
      pnl30: '6,657.20',
      rho: '-0.98',
      dv01: '2.78',
      divRho$: '277.67',
      optionRic: 'LFE7600B0.L',
      created: '',
      openclose: '',
      settlementType: ''
    },
    {
      lastUpdate: '',
      underlier: '',
      spotFut: 'f',
      basis: '-0.76',
      spotUsed: '7,574.26',
      ae: '',
      productType: '',
      expiry: '',
      expiryFull: '',
      strike: '7500',
      strikeP: '100.34%',
      pc: 'C',
      ratio: '-1',
      bid: '',
      premium: '-62.81',
      ask: '',
      vol: '11.02%',
      volOffset: '',
      delta: '41.12%',
      size: '-1',
      contract: '10',
      delta$: '407,368.94',
      gamma$: '135,900.61',
      vega: '8.3',
      vega$: '1,085.37',
      theta$: '-96.83',
      theta: '-1.5',
      fx$: '1,3079',
      premP: '0.83%',
      premT: '6,280.70',
      skew$: '-15.75',
      smile$: '-0.30',
      volGeoSkew: '-0.12',
      volGeoSmile: '0',
      hedgeRic: '',
      futsMat: '',
      futsCt: '10',
      vanna$: '10.93',
      volga$: '2.56',
      pnl10: '-8,213.98',
      pnl20: '-8,213.21',
      pnl30: '-8,213.21',
      rho: '2.47',
      dv01: '3.23',
      divRho$: '322.70',
      optionRic: 'LFE7600B0.L',
      created: '',
      openclose: '',
      settlementType: ''
    },
    {
      lastUpdate: '17:03:09',
      underlier: '.FTSE',
      spotFut: 'f',
      basis: '-0.76',
      spotUsed: '7,574.26',
      ae: 'E',
      productType: 'CS',
      expiry: 'Feb20',
      expiryFull: 'Fri 21 Feb 20',
      strike: '7600 / 7500',
      strikeP: '',
      pc: 'CS',
      ratio: '1 / -1',
      bid: '',
      premium: '-119.05',
      ask: '',
      vol: '',
      volOffset: '',
      delta: '59%',
      size: '1',
      contract: '',
      delta$: '-58,446.99',
      gamma$: '-12,526.1',
      vega: '8.3',
      vega$: '-108.54',
      theta$: '-21.33',
      theta: '-1.63',
      fx$: '1,3079',
      premP: '1.57%',
      premT: '1,190.51',
      skew$: '-3.57',
      smile$: '-0.54',
      volGeoSkew: '-0.27',
      volGeoSmile: '0.04',
      hedgeRic: 'FFIH0',
      futsMat: '2020-03-20',
      futsCt: '10',
      vanna$: '10.56',
      volga$: '-0.98',
      pnl10: '1,556.51',
      pnl20: '1,557.01',
      pnl30: '1,557.01',
      rho: '3.44',
      dv01: '-0.45',
      divRho$: '-45.03',
      optionRic: 'LFE7500B0.L',
      created: '2020-01-24 16:54',
      openclose: 'Open',
      settlementType: 'Cash'
    }
  ]
}
